# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        aws_access_key_id: "ASIAZLLIXLS7AMWLWUZP"
        aws_secret_access_key: "EQCZHmxg/CRlAzogYBF6H6/aoUuutGaGxx6RxVsF"
        aws_session_token: "IQoJb3JpZ2luX2VjEFIaCXVzLXdlc3QtMiJGMEQCICF3Qu+q8pZHKaeWttKIbIR+hJ2wl3/vlrMHtxSvf0LsAiA86QZODYKzT95qDrWvsLssGPvhGQoUJ1JfGg8uL99xVirCAgir//////////8BEAEaDDY0Mjg1NDExNjU0MiIM5B1lM90zmdmYaSegKpYChJoOz3Jpc3EU73l1H9urtqKomXZ1Lm8v2teBy6+IY4oygkNoNEYnpZwIGpp9/gNmYe5MO4RVcNHsbM9tJ8gHAPhAaWXu4WEyojDFSMwlDsRdn0vue1cZnBzQlqGPwEC+rXg3a9F8xqfmN1gwwlKtF6eeH3r/m2d+X8OWdcdjm5raPmUrCPzzGuLwJtyew5l16ZFtESvhoC+3Qm7fvj5sZls6iwqCYQHRlcTF32XSz4QFv8PxKwSgCsXR6yYVGqMLdRu8B+aUI5Pcsq64AwwCeuLEsZ3skpXWsiQnYh54IeFkKcY5jnXWXn0cNCdY78U5A2v4MdsRb1VEMGXbuTAg1+bCc+ydpatduUPPlw9kLBEsPruakeYw+sH2vgY6ngH/Py8nwCyS6UlF3fa2HowvuIH9SoFEvCibXnuObHsZ8UpGjiK0k5ePMJl2v6x7UoaG2f4BKmZ4Y/cOCOaCX1IyZGAeSQoTbRNhp4jCX+VkVWxCHthBlsNRC0Gr28YvApzAPEUuGbLLIYzSQlX2M+OyPwgPwrBtKepqsCZkyr+lSQusG3V/Xd64EWq9+UPCFEaW6MO+G8J72J3+M9VJog=="
       
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
 # Sube los archivos al bucket S3
    - name: Deploy to S3
      run: |
        aws s3 sync ./build/ s3://alomedelete/ --delete
